# Generated by Django 3.0.3 on 2020-02-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
