# Generated by Django 3.0.3 on 2020-02-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200229_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
